### PR TITLE
Issue 133 compress images

### PR DESCRIPTION
**Pull request by benedictSchurwanz**

### CODE REVIEW

**Review by allie-rae — CHANGES_REQUESTED** [review]
The images were compressed a bit too much -- the photos are turning up blurry. Looks like the height/width of the photos is too small. The matches page photos on my laptop are showing up at 566px by 566px and that's a fairly small screen -- images might get larger on larger screens. 

When you change images, it's important to look through the UI to double check that there isn't any distortion or blurring. It's also helpful to use the largest monitor possible, so you know the images are at their maximum sizes and are still crisp and clear. 

Most of the time, I'd recommend compressing images without changing their height/width. I'd only recommend changing the height/width if you've done the math and you're 100% certain about what the largest possible image dimensions are so you don't accidentally make them smaller than that.

**Comment by benedictSchurwanz** [comment]
The tool at imagecompressor.com did a better job of automatically optimizing size while maintaining image quality. The other one I found at https://fengyuanchen.github.io/compressorjs/ has manual changes rather than automatic.

**Comment by benedictSchurwanz** [comment]
And I just realized that images can be compressed to smaller sizes _without_ changing pixel density. That blows my mind.

**Review by allie-rae — APPROVED** [review]
Looks good!

**Pull request merged**
